Repository HumanSignal/label-studio-ml-backend, pull requests merged in 2024-05, with the labels that each got.

#529 feat: DIA-1061: Add START_TRAINING to fit in models
  label_studio_ml/examples/bert_classifier/model.py
  label_studio_ml/examples/huggingface_ner/model.py
  label_studio_ml/examples/sklearn_text_classifier/model.py
Labels: feat

#538 fix: Add doc string to default model with START_TRAINING
  label_studio_ml/default_configs/model.py
Labels: fix

#541 docs: Updating frontmatter for styling changes
  label_studio_ml/examples/bert_classifier/README.md
  label_studio_ml/examples/easyocr/README.md
  label_studio_ml/examples/flair/README.md
  label_studio_ml/examples/gliner/README.md
  label_studio_ml/examples/grounding_dino/README.md
  label_studio_ml/examples/huggingface_llm/README.md
  label_studio_ml/examples/huggingface_ner/README.md
  label_studio_ml/examples/interactive_substring_matching/README.md
  label_studio_ml/examples/langchain_search_agent/README.md
  label_studio_ml/examples/llm_interactive/README.md
  label_studio_ml/examples/mmdetection-3/README.md
  label_studio_ml/examples/nemo_asr/README.md
  label_studio_ml/examples/segment_anything_model/README.md
  label_studio_ml/examples/sklearn_text_classifier/README.md
  label_studio_ml/examples/spacy/README.md
  label_studio_ml/examples/tesseract/README.md
Labels: docs

#546 fix: RND-71: Support cloud storage links resolution for textual ML backends
  label_studio_ml/examples/bert_classifier/model.py
  label_studio_ml/examples/flair/model.py
  label_studio_ml/examples/huggingface_llm/model.py
  label_studio_ml/examples/huggingface_ner/model.py
  label_studio_ml/examples/interactive_substring_matching/model.py
  label_studio_ml/examples/langchain_search_agent/model.py
  label_studio_ml/examples/llm_interactive/model.py
  label_studio_ml/examples/sklearn_text_classifier/model.py
  label_studio_ml/examples/spacy/model.py
  label_studio_ml/model.py
  label_studio_ml/utils.py
  tests/test_unit_model.py
Labels: fix
