Repository HumanSignal/label-studio-ml-backend, pull requests merged in 2024-04, with the labels that each got.

#469 fix: LEAP-903: Add bert_classifier model
  label_studio_ml/default_configs/model.py
  label_studio_ml/examples/bert/.dockerignore
  label_studio_ml/examples/bert/Dockerfile
  label_studio_ml/examples/bert/README.md
  label_studio_ml/examples/bert/_wsgi.py
  label_studio_ml/examples/bert/bert_classifier.py
  label_studio_ml/examples/bert/docker-compose.yml
  label_studio_ml/examples/bert/requirements.txt
  label_studio_ml/examples/bert/supervisord.conf
  label_studio_ml/examples/bert/utils.py
  label_studio_ml/examples/bert/uwsgi.ini
  label_studio_ml/examples/bert_classifier/Dockerfile
  label_studio_ml/examples/bert_classifier/README.md
  label_studio_ml/examples/bert_classifier/_wsgi.py
  label_studio_ml/examples/bert_classifier/docker-compose.yml
  label_studio_ml/examples/bert_classifier/model.py
  label_studio_ml/examples/bert_classifier/requirements-base.txt
  label_studio_ml/examples/bert_classifier/requirements-test.txt
  label_studio_ml/examples/bert_classifier/requirements.txt
  label_studio_ml/examples/bert_classifier/test_api.py
  label_studio_ml/examples/electra/.dockerignore
  label_studio_ml/examples/electra/Dockerfile
  label_studio_ml/examples/electra/README.md
  label_studio_ml/examples/electra/docker-compose.yml
  label_studio_ml/examples/electra/electra.py
  label_studio_ml/examples/electra/requirements.txt
  label_studio_ml/examples/electra/supervisord.conf
  label_studio_ml/examples/electra/uwsgi.ini
  label_studio_ml/ls_io.py
Labels: fix

#479 fix: LEAP-902: Fix EasyOCR implementation
  label_studio_ml/examples/easyocr/.dockerignore
  label_studio_ml/examples/easyocr/Dockerfile
  label_studio_ml/examples/easyocr/README.md
  label_studio_ml/examples/easyocr/_wsgi.py
  label_studio_ml/examples/easyocr/docker-compose.yml
  label_studio_ml/examples/easyocr/easyocr_labeling.py
  label_studio_ml/examples/easyocr/label_mappings.json
  label_studio_ml/examples/easyocr/model.py
  label_studio_ml/examples/easyocr/requirements-base.txt
  label_studio_ml/examples/easyocr/requirements-test.txt
  label_studio_ml/examples/easyocr/requirements.txt
  label_studio_ml/examples/easyocr/supervisord.conf
  label_studio_ml/examples/easyocr/test_api.py
  label_studio_ml/examples/easyocr/uwsgi.ini
  label_studio_ml/model.py
Labels: fix

#481 fix: LEAP-934: Remove dummy examples, fix simple_text_classifier
  label_studio_ml/examples/dummy_model/.dockerignore
  label_studio_ml/examples/dummy_model/Dockerfile
  label_studio_ml/examples/dummy_model/README.md
  label_studio_ml/examples/dummy_model/docker-compose.yml
  label_studio_ml/examples/dummy_model/dummy_model.py
  label_studio_ml/examples/dummy_model/requirements.txt
  label_studio_ml/examples/dummy_model/supervisord.conf
  label_studio_ml/examples/dummy_model/uwsgi.ini
  label_studio_ml/examples/pytorch_transfer_learning/.dockerignore
  label_studio_ml/examples/pytorch_transfer_learning/Dockerfile
  label_studio_ml/examples/pytorch_transfer_learning/README.md
  label_studio_ml/examples/pytorch_transfer_learning/_wsgi.py
  label_studio_ml/examples/pytorch_transfer_learning/docker-compose.yml
  label_studio_ml/examples/pytorch_transfer_learning/pytorch_transfer_learning.py
  label_studio_ml/examples/pytorch_transfer_learning/requirements.txt
  label_studio_ml/examples/pytorch_transfer_learning/supervisord.conf
  label_studio_ml/examples/pytorch_transfer_learning/uwsgi.ini
  label_studio_ml/examples/simple_text_classifier/.dockerignore
  label_studio_ml/examples/simple_text_classifier/Dockerfile
  label_studio_ml/examples/simple_text_classifier/README.md
  label_studio_ml/examples/simple_text_classifier/_wsgi.py
  label_studio_ml/examples/simple_text_classifier/docker-compose.yml
  label_studio_ml/examples/simple_text_classifier/requirements.txt
  label_studio_ml/examples/simple_text_classifier/simple_text_classifier.py
  label_studio_ml/examples/sklearn_text_classifier/Dockerfile
  label_studio_ml/examples/sklearn_text_classifier/README.md
  label_studio_ml/examples/sklearn_text_classifier/_wsgi.py
  label_studio_ml/examples/sklearn_text_classifier/docker-compose.yml
  label_studio_ml/examples/sklearn_text_classifier/model.py
  label_studio_ml/examples/sklearn_text_classifier/requirements-base.txt
  label_studio_ml/examples/sklearn_text_classifier/requirements-test.txt
  label_studio_ml/examples/sklearn_text_classifier/requirements.txt
  label_studio_ml/examples/sklearn_text_classifier/test_api.py
  label_studio_ml/examples/tensorflow/.dockerignore
  label_studio_ml/examples/tensorflow/Dockerfile
  label_studio_ml/examples/tensorflow/_wsgi.py
  label_studio_ml/examples/tensorflow/docker-compose.yml
  label_studio_ml/examples/tensorflow/mobilenet_finetune.py
  label_studio_ml/examples/tensorflow/requirements.txt
  label_studio_ml/examples/the_simplest_backend/.dockerignore
  label_studio_ml/examples/the_simplest_backend/Dockerfile
  label_studio_ml/examples/the_simplest_backend/README.md
  label_studio_ml/examples/the_simplest_backend/_wsgi.py
  label_studio_ml/examples/the_simplest_backend/docker-compose.yml
  label_studio_ml/examples/the_simplest_backend/model.py
  label_studio_ml/examples/the_simplest_backend/requirements.txt
  label_studio_ml/model.py
  requirements.txt
Labels: fix

#480 ci: PLT-296: Add Docs workflow
  .github/workflows/docs.yml
Labels: ci

#488 fix: LEAP-937: Replace "substring_matching" with "interactive_substring_matching"
  label_studio_ml/examples/interactive_substring_matching/Dockerfile
  label_studio_ml/examples/interactive_substring_matching/README.md
  label_studio_ml/examples/interactive_substring_matching/_wsgi.py
  label_studio_ml/examples/interactive_substring_matching/docker-compose.yml
  label_studio_ml/examples/interactive_substring_matching/model.py
  label_studio_ml/examples/interactive_substring_matching/requirements-base.txt
  label_studio_ml/examples/interactive_substring_matching/requirements-test.txt
  label_studio_ml/examples/interactive_substring_matching/requirements.txt
  label_studio_ml/examples/interactive_substring_matching/test_api.py
  label_studio_ml/examples/substring_matching/.dockerignore
  label_studio_ml/examples/substring_matching/Dockerfile
  label_studio_ml/examples/substring_matching/docker-compose.yml
  label_studio_ml/examples/substring_matching/requirements.txt
  label_studio_ml/examples/substring_matching/substring_matching.py
Labels: fix

#489 fix: LEAP-938: fix NeMo ASR ML backend
  README.md
  label_studio_ml/examples/nemo/.dockerignore
  label_studio_ml/examples/nemo/Dockerfile
  label_studio_ml/examples/nemo/README.md
  label_studio_ml/examples/nemo/asr.py
  label_studio_ml/examples/nemo/docker-compose.yml
  label_studio_ml/examples/nemo/requirements.txt
  label_studio_ml/examples/nemo/supervisord.conf
  label_studio_ml/examples/nemo/uwsgi.ini
  label_studio_ml/examples/nemo_asr/Dockerfile
  label_studio_ml/examples/nemo_asr/README.md
  label_studio_ml/examples/nemo_asr/_wsgi.py
  label_studio_ml/examples/nemo_asr/docker-compose.yml
  label_studio_ml/examples/nemo_asr/model.py
  label_studio_ml/examples/nemo_asr/requirements-base.txt
  label_studio_ml/examples/nemo_asr/requirements-test.txt
  label_studio_ml/examples/nemo_asr/requirements.txt
  label_studio_ml/examples/nemo_asr/test_api.py
Labels: fix

#492 fix: Get local path in LabelStudioML
  label_studio_ml/model.py
Labels: fix

#477 chore: Remove old mmdetection model, update mmdetection-3
  README.md
  label_studio_ml/default_configs/docker-compose.yml
  label_studio_ml/default_configs/model.py
  label_studio_ml/examples/easyocr/docker-compose.yml
  label_studio_ml/examples/easyocr/model.py
  label_studio_ml/examples/grounding_dino/dino.py
  label_studio_ml/examples/mmdetection-3/Dockerfile
  label_studio_ml/examples/mmdetection-3/_wsgi.py
  label_studio_ml/examples/mmdetection-3/docker-compose.yml
  label_studio_ml/examples/mmdetection-3/mmdetection.py
  label_studio_ml/examples/mmdetection-3/requirements-base.txt
  label_studio_ml/examples/mmdetection-3/requirements-test.txt
  label_studio_ml/examples/mmdetection-3/requirements.txt
  label_studio_ml/examples/mmdetection-3/test_model.py
  label_studio_ml/examples/mmdetection/.dockerignore
  label_studio_ml/examples/mmdetection/Dockerfile
  label_studio_ml/examples/mmdetection/README.md
  label_studio_ml/examples/mmdetection/_base_/datasets/coco_detection.py
  label_studio_ml/examples/mmdetection/_base_/default_runtime.py
  label_studio_ml/examples/mmdetection/_base_/models/faster_rcnn_r50_fpn.py
  label_studio_ml/examples/mmdetection/_base_/schedules/schedule_1x.py
  label_studio_ml/examples/mmdetection/_wsgi.py
  label_studio_ml/examples/mmdetection/docker-compose.yml
  label_studio_ml/examples/mmdetection/faster_rcnn_r50_fpn_1x_coco.py
  label_studio_ml/examples/mmdetection/mmdetection.py
  label_studio_ml/examples/mmdetection/requirements.txt
  label_studio_ml/examples/mmdetection/supervisord.conf
  label_studio_ml/examples/mmdetection/uwsgi.ini
  label_studio_ml/examples/nemo_asr/docker-compose.yml
  label_studio_ml/examples/nemo_asr/model.py
  label_studio_ml/examples/segment_anything_model/README.md
  label_studio_ml/examples/segment_anything_model/docker-compose.yml
  label_studio_ml/examples/segment_anything_model/model.py
  label_studio_ml/examples/segment_anything_model/sam_predictor.py
  label_studio_ml/examples/tesseract/docker-compose.yml
  label_studio_ml/examples/tesseract/tesseract.py
  label_studio_ml/utils.py
Labels: chore

#494 fix: Readme for mmdetection-3 and fix dino with expections
  label_studio_ml/examples/grounding_dino/dino.py
  label_studio_ml/examples/mmdetection-3/README.md
  label_studio_ml/examples/mmdetection-3/screenshot.png
Labels: fix

#496 fix: LEAP-932: Having pulled suggestions from ML backend causes validation on Labeling Interface
  label_studio_ml/examples/grounding_dino/README.md
  label_studio_ml/examples/grounding_dino/dino.py
  label_studio_ml/examples/grounding_dino/docker-compose.yml
Labels: fix

#522 fix: Rename default NewModel classes
  label_studio_ml/examples/bert_classifier/_wsgi.py
  label_studio_ml/examples/bert_classifier/model.py
  label_studio_ml/examples/bert_classifier/test_api.py
  label_studio_ml/examples/easyocr/_wsgi.py
  label_studio_ml/examples/easyocr/model.py
  label_studio_ml/examples/easyocr/test_api.py
  label_studio_ml/examples/flair/_wsgi.py
  label_studio_ml/examples/flair/model.py
  label_studio_ml/examples/flair/test_api.py
  label_studio_ml/examples/huggingface_llm/_wsgi.py
  label_studio_ml/examples/huggingface_llm/model.py
  label_studio_ml/examples/huggingface_llm/test_api.py
  label_studio_ml/examples/huggingface_ner/_wsgi.py
  label_studio_ml/examples/huggingface_ner/model.py
  label_studio_ml/examples/huggingface_ner/test_api.py
  label_studio_ml/examples/interactive_substring_matching/_wsgi.py
  label_studio_ml/examples/interactive_substring_matching/model.py
  label_studio_ml/examples/interactive_substring_matching/test_api.py
  label_studio_ml/examples/langchain_search_agent/_wsgi.py
  label_studio_ml/examples/langchain_search_agent/model.py
  label_studio_ml/examples/langchain_search_agent/test_api.py
  label_studio_ml/examples/nemo_asr/_wsgi.py
  label_studio_ml/examples/nemo_asr/model.py
  label_studio_ml/examples/nemo_asr/test_api.py
  label_studio_ml/examples/sklearn_text_classifier/_wsgi.py
  label_studio_ml/examples/sklearn_text_classifier/model.py
  label_studio_ml/examples/sklearn_text_classifier/test_api.py
Labels: fix

#523 fix: Add model version in all ML backend examples
  label_studio_ml/examples/bert_classifier/model.py
  label_studio_ml/examples/easyocr/model.py
  label_studio_ml/examples/flair/README.md
  label_studio_ml/examples/flair/model.py
  label_studio_ml/examples/flair/test_api.py
  label_studio_ml/examples/grounding_dino/dino.py
  label_studio_ml/examples/huggingface_llm/model.py
  label_studio_ml/examples/huggingface_llm/test_api.py
  label_studio_ml/examples/huggingface_ner/model.py
  label_studio_ml/examples/huggingface_ner/test_api.py
  label_studio_ml/examples/interactive_substring_matching/model.py
  label_studio_ml/examples/langchain_search_agent/model.py
  label_studio_ml/examples/mmdetection-3/Dockerfile
  label_studio_ml/examples/mmdetection-3/mmdetection.py
  label_studio_ml/examples/mmdetection-3/requirements.txt
  label_studio_ml/examples/mmdetection-3/test_model.py
  label_studio_ml/examples/nemo_asr/model.py
  label_studio_ml/examples/nemo_asr/test_api.py
  label_studio_ml/examples/segment_anything_model/model.py
  label_studio_ml/examples/sklearn_text_classifier/model.py
  label_studio_ml/examples/sklearn_text_classifier/test_api.py
  label_studio_ml/examples/spacy/model.py
  label_studio_ml/examples/spacy/test_api.py
  label_studio_ml/examples/tesseract/tesseract.py
Labels: fix

#527 docs: DOC-208: Note on concurrent request errors
  README.md
Labels: docs

#476 docs: Copy editing readme files and adding front matter for tutorials
  README.md
  label_studio_ml/examples/bert_classifier/README.md
  label_studio_ml/examples/easyocr/README.md
  label_studio_ml/examples/flair/README.md
  label_studio_ml/examples/grounding_dino/README.md
  label_studio_ml/examples/huggingface_llm/README.md
  label_studio_ml/examples/huggingface_ner/README.md
  label_studio_ml/examples/interactive_substring_matching/README.md
  label_studio_ml/examples/langchain_search_agent/README.md
  label_studio_ml/examples/llm_interactive/README.md
  label_studio_ml/examples/mmdetection-3/README.md
  label_studio_ml/examples/nemo_asr/README.md
  label_studio_ml/examples/segment_anything_model/README.md
  label_studio_ml/examples/sklearn_text_classifier/README.md
  label_studio_ml/examples/spacy/README.md
  label_studio_ml/examples/tesseract/README.md
Labels: docs
