Repository HumanSignal/label-studio-ml-backend, pull requests merged in 2024-08, with the labels that each got.

#591 feat: RND-111: Add SegmentAnything2 support to LabelStudio
  .github/docker-build-config.yml
  .github/workflows/tests.yml
  label_studio_ml/examples/segment_anything_2/.dockerignore
  label_studio_ml/examples/segment_anything_2/Dockerfile
  label_studio_ml/examples/segment_anything_2/README.md
  label_studio_ml/examples/segment_anything_2/_wsgi.py
  label_studio_ml/examples/segment_anything_2/docker-compose.yml
  label_studio_ml/examples/segment_anything_2/model.py
  label_studio_ml/examples/segment_anything_2/requirements-base.txt
  label_studio_ml/examples/segment_anything_2/requirements-test.txt
  label_studio_ml/examples/segment_anything_2/requirements.txt
  label_studio_ml/examples/segment_anything_2/start.sh
  label_studio_ml/examples/segment_anything_2/test_api.py
Labels: feat

#595 docs: Update documentation for segment_anything_2_image
  .github/docker-build-config.yml
  .github/workflows/build.yml
  .github/workflows/tests.yml
  README.md
  label_studio_ml/examples/segment_anything_2_image/.dockerignore
  label_studio_ml/examples/segment_anything_2_image/Dockerfile
  label_studio_ml/examples/segment_anything_2_image/README.md
  label_studio_ml/examples/segment_anything_2_image/_wsgi.py
  label_studio_ml/examples/segment_anything_2_image/docker-compose.yml
  label_studio_ml/examples/segment_anything_2_image/model.py
  label_studio_ml/examples/segment_anything_2_image/requirements-base.txt
  label_studio_ml/examples/segment_anything_2_image/requirements-test.txt
  label_studio_ml/examples/segment_anything_2_image/requirements.txt
  label_studio_ml/examples/segment_anything_2_image/start.sh
  label_studio_ml/examples/segment_anything_2_image/test_api.py
  label_studio_ml/examples/segment_anything_model/README.md
Labels: title needs formatting, docs

#598 test: Update SAM2_video runner size
  .github/workflows/tests.yml
Labels: test

#600 fix: Remove Personal Info from watsonx docker compose
  label_studio_ml/examples/watsonx_llm/docker-compose.yml
  label_studio_ml/examples/watsonx_llm/test_api.py
Labels: fix, ci

#604 ci: PLT-448: Improve docker build config
  .github/docker-build-config.yml
  .github/workflows/build.yml
  .github/workflows/tests.yml
Labels: ci

#605 fix: Model_wsgi to wsgi
  label_studio_ml/server.py
Labels: fix

#610 docs: Fixes and adding front matter to example README files
  label_studio_ml/examples/grounding_sam/README.md
  label_studio_ml/examples/segment_anything_2_image/README.md
  label_studio_ml/examples/segment_anything_2_video/README.md
  label_studio_ml/examples/tesseract/README.md
  label_studio_ml/examples/watsonx_llm/README.md
Labels: docs

#612 docs: ReadMe updates for tutorials
  label_studio_ml/examples/segment_anything_2_image/README.md
  label_studio_ml/examples/segment_anything_2_video/README.md
  label_studio_ml/examples/watsonx_llm/README.md
Labels: docs

#614 fix: Don't run tests when md files are changed
  .github/workflows/tests.yml
Labels: fix
