Repository HumanSignal/label-studio-ml-backend, pull requests merged in 2024-03, with the labels that each got.

#437 feat: Basic Auth support, Azure openAI, Semver, and using LabelInterface
  .github/workflows/tests.yml
  Makefile
  label_studio_ml/__init__.py
  label_studio_ml/api.py
  label_studio_ml/default_configs/_wsgi.py.tmpl
  label_studio_ml/default_configs/model.py
  label_studio_ml/examples/easyocr/easyocr_labeling.py
  label_studio_ml/examples/llm_interactive/README.md
  label_studio_ml/examples/llm_interactive/docker-compose.yml
  label_studio_ml/examples/llm_interactive/model.py
  label_studio_ml/examples/llm_interactive/requirements.txt
  label_studio_ml/examples/ner_using_transformers/.dockerignore
  label_studio_ml/examples/ner_using_transformers/Dockerfile
  label_studio_ml/examples/ner_using_transformers/README.md
  label_studio_ml/examples/ner_using_transformers/_wsgi.py
  label_studio_ml/examples/ner_using_transformers/docker-compose.yml
  label_studio_ml/examples/ner_using_transformers/ner.py
  label_studio_ml/examples/ner_using_transformers/requirements.txt
  label_studio_ml/examples/ner_using_transformers/supervisord.conf
  label_studio_ml/examples/ner_using_transformers/utils.py
  label_studio_ml/examples/ner_using_transformers/uwsgi.ini
  label_studio_ml/examples/openai/openai_predictor.py
  label_studio_ml/examples/pytorch_transfer_learning/pytorch_transfer_learning.py
  label_studio_ml/examples/the_simplest_backend/model.py
  label_studio_ml/model.py
  label_studio_ml/response.py
  label_studio_ml/server.py
  label_studio_ml/utils.py
  requirements.txt
  tests/__init__.py
  tests/requirements-test.txt
  tests/test_api.py
  tests/test_basic.py
  tests/test_response.py
Labels: feat

#454 Add run-per-ml-backend tests step in CI
  .github/workflows/tests.yml
Labels: title needs formatting

#458 Make base dockerfile
  .github/workflows/tests.yml
  label_studio_ml/default_configs/Dockerfile
  label_studio_ml/default_configs/docker-compose.yml
  label_studio_ml/default_configs/requirements-base.txt
  label_studio_ml/default_configs/requirements-test.txt
  label_studio_ml/default_configs/requirements.txt
  label_studio_ml/examples/flair/requirements.txt
  label_studio_ml/server.py
Labels: title needs formatting

#455 fix: LEAP-874: Fix usability issues with Interactive tesseract OCR
  label_studio_ml/examples/tesseract/README.md
  label_studio_ml/examples/tesseract/docker-compose.yml
  label_studio_ml/examples/tesseract/example.env
  label_studio_ml/examples/tesseract/tesseract.py
  label_studio_ml/examples/tesseract/test_model.py
Labels: fix

#457 fix: SpaCy model build and run
  label_studio_ml/examples/spacy/Dockerfile
  label_studio_ml/examples/spacy/README.md
  label_studio_ml/examples/spacy/docker-compose.yml
  label_studio_ml/examples/spacy/model.py
  label_studio_ml/examples/spacy/requirements-base.txt
  label_studio_ml/examples/spacy/requirements-test.txt
  label_studio_ml/examples/spacy/requirements.txt
  label_studio_ml/examples/spacy/test_api.py
Labels: fix

#456 Fix URL checks for file retriever
  requirements.txt
Labels: title needs formatting

#459 fix: Fix flair inference for NER
  label_studio_ml/examples/flair/.dockerignore
  label_studio_ml/examples/flair/Dockerfile
  label_studio_ml/examples/flair/README.md
  label_studio_ml/examples/flair/_wsgi.py
  label_studio_ml/examples/flair/docker-compose.yml
  label_studio_ml/examples/flair/model.py
  label_studio_ml/examples/flair/ner_ml_backend.py
  label_studio_ml/examples/flair/readme.md
  label_studio_ml/examples/flair/requirements-base.txt
  label_studio_ml/examples/flair/requirements-test.txt
  label_studio_ml/examples/flair/requirements.txt
  label_studio_ml/examples/flair/supervisord.conf
  label_studio_ml/examples/flair/test_api.py
  label_studio_ml/examples/flair/uwsgi.ini
Labels: fix

#461 fix: Add mmdetection-3 tests
  label_studio_ml/examples/mmdetection-3/Dockerfile
  label_studio_ml/examples/mmdetection-3/mmdetection.py
  label_studio_ml/examples/mmdetection-3/requirements.txt
  label_studio_ml/examples/mmdetection-3/test_model.py
  setup.py
Labels: fix

#463 ci: PLT-285: Support build with TEST_ENV packages
  label_studio_ml/default_configs/Dockerfile
  label_studio_ml/default_configs/docker-compose.yml
  label_studio_ml/examples/flair/Dockerfile
  label_studio_ml/examples/flair/docker-compose.yml
Labels: ci

#452 fix: LEAP-861: Resolve CUDA runtime error issue
  label_studio_ml/default_configs/docker-compose.yml
  label_studio_ml/examples/segment_anything_model/Dockerfile
  label_studio_ml/examples/segment_anything_model/README.md
  label_studio_ml/examples/segment_anything_model/docker-compose.yml
  label_studio_ml/examples/segment_anything_model/download_models.sh
  label_studio_ml/examples/segment_anything_model/requirements-base.txt
  label_studio_ml/examples/segment_anything_model/requirements-test.txt
  label_studio_ml/examples/segment_anything_model/sam_predictor.py
  label_studio_ml/examples/segment_anything_model/start.sh
  label_studio_ml/examples/segment_anything_model/test_predict.py
  label_studio_ml/model.py
Labels: fix

#453 fix: LEAP-865: Fix GroundingDINO setup
  label_studio_ml/examples/grounding_dino/Dockerfile
  label_studio_ml/examples/grounding_dino/README.md
  label_studio_ml/examples/grounding_dino/dino.py
  label_studio_ml/examples/grounding_dino/docker-compose.yml
  label_studio_ml/examples/grounding_dino/requirements-test.txt
  label_studio_ml/examples/grounding_dino/requirements.txt
  label_studio_ml/examples/grounding_dino/start.sh
  label_studio_ml/examples/grounding_dino/test_api.py
Labels: fix
