Repository HumanSignal/label-studio-ml-backend, pull requests merged in 2024-06, with the labels that each got.

#549 fix: DIA-1061: Add START_TRAINING in api
  label_studio_ml/api.py
Labels: fix

#555 docs: Update README.md, add LABEL_STUDIO_URL to quickstart
  README.md
Labels: docs

#559 fix: Spacy pydantic deps
  label_studio_ml/examples/langchain_search_agent/Dockerfile
  label_studio_ml/examples/spacy/Dockerfile
Labels: fix

#562 ci: PLT-377: Remove unused requirements.txt
  label_studio_ml/examples/requirements.txt
Labels: ci

#563 ci: Update CODEOWNERS
  .github/CODEOWNERS
Labels: ci

#565 fix: DIA-1061: Start training instead of project update
  label_studio_ml/model.py
Labels: fix

#569 docs: Add Ollama to LLM interactive frontmatter
  label_studio_ml/examples/llm_interactive/README.md
Labels: docs

#570 fix: RND-101: Fix ML backend compatibility with sdk>=1
  label_studio_ml/api.py
  label_studio_ml/examples/easyocr/requirements.txt
  label_studio_ml/examples/huggingface_ner/model.py
  label_studio_ml/examples/mmdetection-3/requirements.txt
  label_studio_ml/examples/nemo_asr/requirements.txt
  label_studio_ml/examples/spacy/requirements.txt
  label_studio_ml/model.py
  label_studio_ml/response.py
  label_studio_ml/utils.py
  requirements.txt
  tests/test_response.py
Labels: fix

#574 fix: MMDetection deps with mmcv
  label_studio_ml/examples/mmdetection-3/requirements.txt
Labels: fix
