Repository HumanSignal/label-studio-ml-backend, pull requests merged in 2024-09, with the labels that each got.

#619 docs: Add labeling config to SAM2 for images
  label_studio_ml/examples/segment_anything_2_image/README.md
Labels: docs

#620 fix: Tests for nemo and SAM
  label_studio_ml/examples/nemo_asr/requirements.txt
  label_studio_ml/examples/segment_anything_model/Dockerfile
Labels: fix

#621 fix: Dependencies in YOLO and MMDetection
  label_studio_ml/examples/mmdetection-3/requirements-base.txt
  label_studio_ml/examples/yolo/requirements-base.txt
Labels: fix

#622 fix: Grounding SAM dependencies
  label_studio_ml/examples/grounding_sam/requirements.txt
Labels: fix

#623 docs: Fix Docker command in Tesseract readme and WatsonX frontmatter
  label_studio_ml/examples/tesseract/README.md
  label_studio_ml/examples/watsonx_llm/README.md
Labels: docs

#624 fix: RND-117: YOLO score threshold name
  label_studio_ml/examples/yolo/control_models/base.py
  label_studio_ml/examples/yolo/control_models/choices.py
  label_studio_ml/examples/yolo/control_models/keypoint_labels.py
  label_studio_ml/examples/yolo/control_models/polygon_labels.py
  label_studio_ml/examples/yolo/control_models/rectangle_labels.py
  label_studio_ml/examples/yolo/control_models/rectangle_labels_obb.py
  label_studio_ml/examples/yolo/control_models/timeline_labels.py
  label_studio_ml/examples/yolo/tests/test_choices.py
  label_studio_ml/examples/yolo/tests/test_common.py
  label_studio_ml/examples/yolo/tests/test_keypoint_labels.py
  label_studio_ml/examples/yolo/tests/test_polygon_labels.py
  label_studio_ml/examples/yolo/tests/test_rectangle_labels.py
  label_studio_ml/examples/yolo/tests/test_rectangle_labels_obb.py
  label_studio_ml/model.py
Labels: fix

#533 docs: Add troubleshooting section on accessing LS data
  README.md
  label_studio_ml/examples/nemo_asr/README.md
Labels: docs

#625 docs: Add links to ml-backend directory
  label_studio_ml/examples/bert_classifier/README.md
  label_studio_ml/examples/easyocr/README.md
  label_studio_ml/examples/flair/README.md
  label_studio_ml/examples/gliner/README.md
  label_studio_ml/examples/grounding_dino/README.md
  label_studio_ml/examples/grounding_sam/README.md
  label_studio_ml/examples/huggingface_llm/README.md
  label_studio_ml/examples/huggingface_ner/README.md
  label_studio_ml/examples/interactive_substring_matching/README.md
  label_studio_ml/examples/langchain_search_agent/README.md
  label_studio_ml/examples/llm_interactive/README.md
  label_studio_ml/examples/mmdetection-3/README.md
  label_studio_ml/examples/nemo_asr/README.md
  label_studio_ml/examples/segment_anything_2_image/README.md
  label_studio_ml/examples/segment_anything_2_video/README.md
  label_studio_ml/examples/segment_anything_model/README.md
  label_studio_ml/examples/sklearn_text_classifier/README.md
  label_studio_ml/examples/spacy/README.md
  label_studio_ml/examples/tesseract/README.md
  label_studio_ml/examples/watsonx_llm/README.md
  label_studio_ml/examples/yolo/README.md
Labels: docs

#629 fix: Update requirements-base.txt in yolo
  label_studio_ml/examples/yolo/requirements-base.txt
Labels: fix

#633 fix: Escaping in wsgi template
  label_studio_ml/default_configs/_wsgi.py.tmpl
Labels: fix

#634 fix: Use task id in get_local_path sam2
  label_studio_ml/examples/segment_anything_2_image/model.py
Labels: fix

#637 fix: Keypoints model_index should start with 0
  label_studio_ml/examples/yolo/README.md
  label_studio_ml/examples/yolo/control_models/base.py
  label_studio_ml/examples/yolo/control_models/keypoint_labels.py
  label_studio_ml/examples/yolo/control_models/timeline_labels.py
  label_studio_ml/examples/yolo/control_models/video_rectangle.py
  label_studio_ml/examples/yolo/tests/test_neural_nets.py
  label_studio_ml/examples/yolo/tests/test_timeline_labels.py
  label_studio_ml/examples/yolo/utils/converter.py
  label_studio_ml/examples/yolo/utils/neural_nets.py
Labels: fix

#638 docs: Add more info on how to use YOLO custom models
  label_studio_ml/examples/yolo/README.md
  label_studio_ml/examples/yolo/README_TIMELINE_LABELS.md
Labels: docs

#641 feat: Add YOLO11 docs
  label_studio_ml/examples/yolo/README.md
  label_studio_ml/examples/yolo/control_models/timeline_labels.py
  label_studio_ml/examples/yolo/utils/neural_nets.py
Labels: feat
