Repository HumanSignal/label-studio-ml-backend, pull requests merged in 2025-05, with the labels that each got.

#769 docs: Update README.md for YOLO exports
  label_studio_ml/examples/yolo/README.md
Labels: docs

#775 fix: yolo lap requirements
  label_studio_ml/examples/yolo/requirements.txt
Labels: fix

#711 fix: yolo fix cli.py with project id
  label_studio_ml/examples/yolo/cli.py
Labels: fix

#778 ci: PLT-770: update gitleks
  .github/workflows/gitleaks.yml
Labels: ci
